INSERT INTO `{prefix_}config` (`config_name`, `config_value`) VALUES
('sitename', 'phpC Forum'),
('site_desc', ''),
('msg_flash', '1'),
('msg_smilies', '0'),
('msg_edit_info', '0'),
('msg_interval_flood', '10'),
('msg_min_char_post', '10'),
('subject_per_page', '20'),
('post_per_page', '10'),
('post_is_popular', '25'),
('max_poll_options', '10'),
('max_smilies_per_post', '0'),
('msg_private_activ', '0'),
('max_msg_private', '25'),
('max_destina_msg_private', '10'),
('style', 'default'),
('order_forums', '{1:1{1:2};2:3{1:4}}'),
('register_validation', '1'),
('forum_corbeille', '4'),
('nb_page_search', '10'),
('display_quick_profile', '1'),
('activ_auto_completion', '1'),
('members_per_page', '10'),
('max_char_sign', '1500'),
('head_description', ''),
('head_keywords', ''),
('head_subject', ''),
('head_author', ''),
('max_simult_user', '1'),
('total_post', '1'),
('total_topic', '1'),
('total_users', '1'),
('interval_days_purge_topic_read', '10'),
('subject_maxlength', '80'),
('display_label_poll', '1'),
('admin_note', ''),
('max_width_avatar', '200'),
('max_height_avatar', '200'),
('templates_changed', '0'),
('maxlength_username', '30');

INSERT INTO `{prefix_}design` (`selector_id`, `selector_name`, `selector_type`, `selector_activ`, `name`, `backgroundColor`, `backgroundColor_m`, `exception`, `backgroundImage`, `backgroundImage_m`, `borderColor`, `borderColor_m`, `color`, `color_m`, `backgroundRepeat`, `backgroundRepeat_m`, `fontSize`, `fontSize_m`, `height`, `width`, `width_m`, `height_m`, `borderSize`, `borderSize_m`, `opacity`, `opacity_m`) VALUES
(1, 'body', 0, 1, 'L_BODY', 'B8BABC', 'B8BABC', 'height,text,opacity', 'styles/default/images/body_header.png', 'styles/default/images/body_header.png', 'A859A8', 'A859A8', '', '', 'repeat-x', 'repeat-x', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(2, '#footer', 0, 1, 'L_FOOTER', '', '', NULL, '', '', '', '', '', '', '', '', 11, 11, 23, 0, 0, 23, 0, 0, 0, 0),
(3, '.catrow', 1, 0, 'L_CATROW', 'FFFFFF', 'FFFFFF', 'height', '', '', '', '', '', '', '', '', 13, 13, 0, 0, 0, 0, 0, 0, 100, 100),
(4, '.header_title', 0, 1, 'L_HEADER_TITLE', '', '', NULL, '', '', '', '', '', '', 'repeat-x', 'repeat-x', 12, 12, 45, 0, 0, 45, 0, 0, 100, 100),
(5, '#banner', 0, 1, 'L_BANNER', '', '', NULL, 'styles/default/images/banner.png', 'styles/default/images/banner.png', '', '', '', '', 'no-repeat', 'no-repeat', 0, 0, 132, 0, 0, 132, 0, 0, 0, 1),
(6, '.global_content', 0, 1, 'L_GLOBAL_CONTENT', '', '', 'height', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(7, '.global', 0, 1, 'L_GLOBAL', '', '', 'height', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(8, '.globalbox', 0, 1, 'L_GLOBALBOX', 'FFFFFF', 'FFFFFF', 'height', '', '', '', '', '484848', '484848', '', '', 12, 12, 0, 0, 0, 0, 0, 0, 0, 0),
(9, '.globalbox_l2', 0, 1, 'L_GLOBALBOX_L2', 'E3E3E3', 'E3E3E3', 'height', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(10, '.tooltip', 0, 1, 'L_TOOLTIP', '', '', 'height', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(11, '.title', 0, 1, 'L_TITLE', '', '', NULL, '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(12, '.ariana-pages', 0, 1, 'L_ARIANA', '44474B', '44474B', NULL, '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(13, '.memberlist', 1, 1, 'L_MEMBERLIST', 'EFEFEF', 'EFEFEF', NULL, '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(16, '#confirm', 0, 1, 'L_CONFIRM', '', '', 'height', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(15, '.button_header', 0, 1, 'L_BUTTON_HEADER', '', '', NULL, 'styles/default/images/barre5.png', 'styles/default/images/barre5.png', '454225', '454225', '', '', '', '', 12, 12, 34, 0, 0, 34, 0, 0, 100, 100),
(17, '.report_popup', 0, 1, 'L_REPORT_POPUP', '', '', 'height', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(18, '#body', 0, 1, 'L_BODY_ID', '9A9A9A', '9A9A9A', 'height,opacity,text', 'styles/default/images/body_gradient.png', 'styles/default/images/body_gradient.png', '', '', '', '', 'repeat-x', 'repeat-x', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(19, '.quick_menu', 1, 1, 'L_QUICK_MENU', 'FFFFFF', 'FFFFFF', 'width', '', '', '', '', '000000', '000000', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(20, '.postbox', 1, 0, 'L_POSTBOX', '', '', 'width', '', '', '', '', '', '', '', '', 0, 0, 0, 819, 819, 0, 0, 0, 0, 0),
(21, '.button', 0, 1, 'L_BUTTON', '000000', '000000', 'height,width', '', '', 'FFFFFF', 'FFFFFF', 'FFFFFF', 'FFFFFF', '', '', 9, 9, 0, 0, 0, 0, 1, 1, 0, 0),
(22, '#header', 0, 1, 'L_HEADER', '', '', NULL, '', '', '', '', '', '', '', '', 0, 0, 180, 0, 0, 180, 0, 0, 0, 0),
(26, '.highlight', 1, 1, 'L_HIGHTLIGHT', '', '', 'height,width', '', '', '', '', 'FF0015', 'FF0015', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(23, '.link', 0, 1, 'L_LINK', '', '', 'height,width', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(24, '.select', 0, 1, 'L_SELECT', '080808', '080808', 'height,width', '', '', '', '', 'FFFFFF', 'FFFFFF', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(25, '#body_l2', 0, 1, 'L_BODY_L2', '', '', 'height', 'none', 'none', '', '', '', '', 'no-repeat', 'no-repeat', 0, 0, 0, 846, 846, 0, 0, 0, 0, 0),
(27, '.above', 0, 1, 'L_ABOVE', '', '', 'width', '', '', '', '', 'FFFFFF', 'FFFFFF', '', '', 8, 8, 19, 0, 0, 19, 0, 0, 100, 100),
(28, '.pm-grid > li', 1, 1, 'L_PM_GRID', 'EFEFEF', 'EFEFEF', 'width', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(29, '.pm-grid-title', 1, 1, 'L_PM_GRID_TITLEs', 'EFEFEF', 'EFEFEF', 'width', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO `{prefix_}design_imageset` (`image_id`, `image_name`, `image_filename`, `image_lang`, `image_height`, `image_width`) VALUES
(1, 'new_post', 'new_post.png', 'fr_FR', 0, 0),
(2, 'icon_avatar', 'profile_avatar.png', 'fr_FR', 0, 0),
(3, 'icon_admin', 'profile_admin.png', 'fr_FR', 0, 0),
(4, 'icon_avert', 'profile_avert.png', 'fr_FR', 0, 0),
(5, 'icon_comment', 'profile_comment.png', 'fr_FR', 0, 0),
(6, 'icon_report', 'profile_report.png', 'fr_FR', 0, 0),
(7, 'icon_setting_view', 'profile_setting_display.png', 'fr_FR', 0, 0),
(8, 'icon_setting_personal', 'profile_setting_global.png', 'fr_FR', 0, 0),
(9, 'icon_setting_info', 'profile_setting_info.png', 'fr_FR', 0, 0),
(10, 'icon_sign', 'profile_signature.png', 'fr_FR', 0, 0),
(11, 'icon_setting_post', 'profile_setting_post.png', 'fr_FR', 0, 0),
(12, 'no_new_post', 'no_new_post.png', 'fr_FR', 0, 0),
(13, 'lock', 'lock.png', 'fr_FR', 0, 0),
(14, 'new_pm', 'new_post.png', 'fr_FR', 0, 0),
(15, 'no_new_pm', 'no_new_post.png', 'fr_FR', 0, 0),
(16, 'avatar_default', 'avatar_default.png', 'fr_FR', 0, 0),
(17, 'lightbox_loading', 'lightbox-ico-loading.gif', 'fr_FR', 0, 0),
(18, 'lightbox_close', 'lightbox-btn-close.gif', 'fr_FR', 0, 0),
(19, 'lightbox_prev', 'lightbox-btn-prev.gif', 'fr_FR', 0, 0),
(20, 'lightbox_next', 'lightbox-btn-next.gif', 'fr_FR', 0, 0),
(21, 'star_group', 'star.png', NULL, NULL, NULL),
(22, 'error', 'error.png', NULL, NULL, NULL),
(23, 'icon_topic_latest', 'icon_topic_latest.gif', NULL, NULL, NULL),
(24, 'facebook', 'facebook.png', '', 0, 0),
(25, 'twitter', 'Twitter.png', '', 0, 0),
(26, 'rss', 'rss.gif', NULL, NULL, NULL);

INSERT INTO `{prefix_}groups_permission` (`group_id`, `forum_id`, `group_permission`) VALUES
(1, 1, '1fffffff'),
(2, 1, '5'),
(3, 1, '70ff'),
(4, 1, '1fff97ff'),
(1, 2, '1fffffff'),
(2, 2, '5'),
(3, 2, '70ff'),
(4, 2, '1fff97ff'),
(1, 3, '1bffffff'),
(2, 3, '0'),
(3, 3, '0'),
(4, 3, '89e0005'),
(1, 4, '1bffffff'),
(2, 4, '0'),
(3, 4, '0'),
(4, 4, '89e0005');

INSERT INTO `{prefix_}templates` (`template_id`, `template_title`, `template_filename`, `template_content`, `template_date_modified`, `template_nb_modified`) VALUES
(1, 'L_TPL_CONFIRM', 'confirm.html', '', 0, 0),
(2, 'L_TPL_FORUM_LIST', 'forumlist.html', '', 0, 0),
(3, 'L_TPL_VIEWTOPIC', 'viewtopic_body.html', '', 0, 0),
(4, 'L_TPL_HEADER', 'main_header.html', '', 0, 0),
(5, 'L_TPL_FOOTER', 'main_footer.html', '', 0, 0),
(6, 'L_TPL_ERROR', 'error.html', '', 0, 0),
(7, 'L_TPL_FORUM_DESALLOW', 'forum_desallow.html', '', 0, 0),
(8, 'L_TPL_FORUM_JUMP', 'forumlist_jump.html', '', 0, 0),
(9, 'L_TPL_INDEX', 'index_body.html', '', 0, 0),
(10, 'L_TPL_MEMBERS', 'members.html', '', 0, 0),
(11, 'L_TPL_POSTING', 'posting_body.html', '', 0, 0),
(12, 'L_TPL_AVERTS', 'profile_averts.html', '', 0, 0),
(13, 'L_TPL_PROFILE', 'profile_body.html', '', 0, 0),
(14, 'L_TPL_COMMENTS', 'profile_comments.html', '', 0, 0),
(15, 'L_TPL_FORGET_PASS', 'profile_forget_pass.html', '', 0, 0),
(16, 'L_TPL_LOGIN', 'profile_login.html', '', 0, 0),
(17, 'L_TPL_MANAGE_PROFILE', 'profile_main.html', '', 0, 0),
(18, 'L_TPL_PM', 'profile_pm.html', '', 0, 0),
(19, 'L_TPL_POST_DETAILS', 'profile_post_details.html', '', 0, 0),
(20, 'L_TPL_REGISTER', 'profile_register.html', '', 0, 0),
(21, 'L_TPL_REPORT', 'report.html', '', 0, 0),
(22, 'L_TPL_RSS', 'rss.html', '', 0, 0),
(23, 'L_TPL_SEARCH', 'search.html', '', 0, 0),
(24, 'L_TPL_VIEWFORUM', 'viewforum_body.html', '', 0, 0);
